CREATE TABLE [Bacia]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long,
	[Nome]			Text(50),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Chuvas]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[TipoMedicaoChuvas]			Byte, 
	[Maxima]			Single, 
	[Total]			Single, 
	[DiaMaxima]			Byte, 
	[NumDiasDeChuva]			Byte, 
	[MaximaStatus]			Byte, 
	[TotalStatus]			Byte, 
	[NumDiasDeChuvaStatus]			Byte, 
	[TotalAnual]			Single, 
	[TotalAnualStatus]			Byte, 
	[Chuva01]			Single, 
	[Chuva02]			Single, 
	[Chuva03]			Single, 
	[Chuva04]			Single, 
	[Chuva05]			Single, 
	[Chuva06]			Single, 
	[Chuva07]			Single, 
	[Chuva08]			Single, 
	[Chuva09]			Single, 
	[Chuva10]			Single, 
	[Chuva11]			Single, 
	[Chuva12]			Single, 
	[Chuva13]			Single, 
	[Chuva14]			Single, 
	[Chuva15]			Single, 
	[Chuva16]			Single, 
	[Chuva17]			Single, 
	[Chuva18]			Single, 
	[Chuva19]			Single, 
	[Chuva20]			Single, 
	[Chuva21]			Single, 
	[Chuva22]			Single, 
	[Chuva23]			Single, 
	[Chuva24]			Single, 
	[Chuva25]			Single, 
	[Chuva26]			Single, 
	[Chuva27]			Single, 
	[Chuva28]			Single, 
	[Chuva29]			Single, 
	[Chuva30]			Single, 
	[Chuva31]			Single, 
	[Chuva01Status]			Byte, 
	[Chuva02Status]			Byte, 
	[Chuva03Status]			Byte, 
	[Chuva04Status]			Byte, 
	[Chuva05Status]			Byte, 
	[Chuva06Status]			Byte, 
	[Chuva07Status]			Byte, 
	[Chuva08Status]			Byte, 
	[Chuva09Status]			Byte, 
	[Chuva10Status]			Byte, 
	[Chuva11Status]			Byte, 
	[Chuva12Status]			Byte, 
	[Chuva13Status]			Byte, 
	[Chuva14Status]			Byte, 
	[Chuva15Status]			Byte, 
	[Chuva16Status]			Byte, 
	[Chuva17Status]			Byte, 
	[Chuva18Status]			Byte, 
	[Chuva19Status]			Byte, 
	[Chuva20Status]			Byte, 
	[Chuva21Status]			Byte, 
	[Chuva22Status]			Byte, 
	[Chuva23Status]			Byte, 
	[Chuva24Status]			Byte, 
	[Chuva25Status]			Byte, 
	[Chuva26Status]			Byte, 
	[Chuva27Status]			Byte, 
	[Chuva28Status]			Byte, 
	[Chuva29Status]			Byte, 
	[Chuva30Status]			Byte, 
	[Chuva31Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Chuvas2]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora1]			DateTime, 
	[Hora2]			DateTime, 
	[TipoMedicaoChuvas]			Byte, 
	[Maxima]			Single, 
	[Total]			Single, 
	[DiaMaxima]			Byte, 
	[NumDiasDeChuva]			Byte, 
	[MaximaStatus]			Byte, 
	[TotalStatus]			Byte, 
	[NumDiasDeChuvaStatus]			Byte, 
	[TotalAnual]			Single, 
	[TotalAnualStatus]			Byte, 
	[Chuva01_1]			Single, 
	[Chuva02_1]			Single, 
	[Chuva03_1]			Single, 
	[Chuva04_1]			Single, 
	[Chuva05_1]			Single, 
	[Chuva06_1]			Single, 
	[Chuva07_1]			Single, 
	[Chuva08_1]			Single, 
	[Chuva09_1]			Single, 
	[Chuva10_1]			Single, 
	[Chuva11_1]			Single, 
	[Chuva12_1]			Single, 
	[Chuva13_1]			Single, 
	[Chuva14_1]			Single, 
	[Chuva15_1]			Single, 
	[Chuva16_1]			Single, 
	[Chuva17_1]			Single, 
	[Chuva18_1]			Single, 
	[Chuva19_1]			Single, 
	[Chuva20_1]			Single, 
	[Chuva21_1]			Single, 
	[Chuva22_1]			Single, 
	[Chuva23_1]			Single, 
	[Chuva24_1]			Single, 
	[Chuva25_1]			Single, 
	[Chuva26_1]			Single, 
	[Chuva27_1]			Single, 
	[Chuva28_1]			Single, 
	[Chuva29_1]			Single, 
	[Chuva30_1]			Single, 
	[Chuva31_1]			Single, 
	[Chuva01Status_1]			Byte, 
	[Chuva02Status_1]			Byte, 
	[Chuva03Status_1]			Byte, 
	[Chuva04Status_1]			Byte, 
	[Chuva05Status_1]			Byte, 
	[Chuva06Status_1]			Byte, 
	[Chuva07Status_1]			Byte, 
	[Chuva08Status_1]			Byte, 
	[Chuva09Status_1]			Byte, 
	[Chuva10Status_1]			Byte, 
	[Chuva11Status_1]			Byte, 
	[Chuva12Status_1]			Byte, 
	[Chuva13Status_1]			Byte, 
	[Chuva14Status_1]			Byte, 
	[Chuva15Status_1]			Byte, 
	[Chuva16Status_1]			Byte, 
	[Chuva17Status_1]			Byte, 
	[Chuva18Status_1]			Byte, 
	[Chuva19Status_1]			Byte, 
	[Chuva20Status_1]			Byte, 
	[Chuva21Status_1]			Byte, 
	[Chuva22Status_1]			Byte, 
	[Chuva23Status_1]			Byte, 
	[Chuva24Status_1]			Byte, 
	[Chuva25Status_1]			Byte, 
	[Chuva26Status_1]			Byte, 
	[Chuva27Status_1]			Byte, 
	[Chuva28Status_1]			Byte, 
	[Chuva29Status_1]			Byte, 
	[Chuva30Status_1]			Byte, 
	[Chuva31Status_1]			Byte, 
	[Chuva01_2]			Single, 
	[Chuva02_2]			Single, 
	[Chuva03_2]			Single, 
	[Chuva04_2]			Single, 
	[Chuva05_2]			Single, 
	[Chuva06_2]			Single, 
	[Chuva07_2]			Single, 
	[Chuva08_2]			Single, 
	[Chuva09_2]			Single, 
	[Chuva10_2]			Single, 
	[Chuva11_2]			Single, 
	[Chuva12_2]			Single, 
	[Chuva13_2]			Single, 
	[Chuva14_2]			Single, 
	[Chuva15_2]			Single, 
	[Chuva16_2]			Single, 
	[Chuva17_2]			Single, 
	[Chuva18_2]			Single, 
	[Chuva19_2]			Single, 
	[Chuva20_2]			Single, 
	[Chuva21_2]			Single, 
	[Chuva22_2]			Single, 
	[Chuva23_2]			Single, 
	[Chuva24_2]			Single, 
	[Chuva25_2]			Single, 
	[Chuva26_2]			Single, 
	[Chuva27_2]			Single, 
	[Chuva28_2]			Single, 
	[Chuva29_2]			Single, 
	[Chuva30_2]			Single, 
	[Chuva31_2]			Single, 
	[Chuva01Status_2]			Byte, 
	[Chuva02Status_2]			Byte, 
	[Chuva03Status_2]			Byte, 
	[Chuva04Status_2]			Byte, 
	[Chuva05Status_2]			Byte, 
	[Chuva06Status_2]			Byte, 
	[Chuva07Status_2]			Byte, 
	[Chuva08Status_2]			Byte, 
	[Chuva09Status_2]			Byte, 
	[Chuva10Status_2]			Byte, 
	[Chuva11Status_2]			Byte, 
	[Chuva12Status_2]			Byte, 
	[Chuva13Status_2]			Byte, 
	[Chuva14Status_2]			Byte, 
	[Chuva15Status_2]			Byte, 
	[Chuva16Status_2]			Byte, 
	[Chuva17Status_2]			Byte, 
	[Chuva18Status_2]			Byte, 
	[Chuva19Status_2]			Byte, 
	[Chuva20Status_2]			Byte, 
	[Chuva21Status_2]			Byte, 
	[Chuva22Status_2]			Byte, 
	[Chuva23Status_2]			Byte, 
	[Chuva24Status_2]			Byte, 
	[Chuva25Status_2]			Byte, 
	[Chuva26Status_2]			Byte, 
	[Chuva27Status_2]			Byte, 
	[Chuva28Status_2]			Byte, 
	[Chuva29Status_2]			Byte, 
	[Chuva30Status_2]			Byte, 
	[Chuva31Status_2]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Chuvas24]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[TipoMedicaoChuvas]			Byte, 
	[Maxima]			Single, 
	[Total]			Single, 
	[HoraMaxima]			Byte, 
	[MaximaStatus]			Byte, 
	[TotalStatus]			Byte, 
	[Chuva00]			Single, 
	[Chuva01]			Single, 
	[Chuva02]			Single, 
	[Chuva03]			Single, 
	[Chuva04]			Single, 
	[Chuva05]			Single, 
	[Chuva06]			Single, 
	[Chuva07]			Single, 
	[Chuva08]			Single, 
	[Chuva09]			Single, 
	[Chuva10]			Single, 
	[Chuva11]			Single, 
	[Chuva12]			Single, 
	[Chuva13]			Single, 
	[Chuva14]			Single, 
	[Chuva15]			Single, 
	[Chuva16]			Single, 
	[Chuva17]			Single, 
	[Chuva18]			Single, 
	[Chuva19]			Single, 
	[Chuva20]			Single, 
	[Chuva21]			Single, 
	[Chuva22]			Single, 
	[Chuva23]			Single, 
	[Chuva00Status]			Byte, 
	[Chuva01Status]			Byte, 
	[Chuva02Status]			Byte, 
	[Chuva03Status]			Byte, 
	[Chuva04Status]			Byte, 
	[Chuva05Status]			Byte, 
	[Chuva06Status]			Byte, 
	[Chuva07Status]			Byte, 
	[Chuva08Status]			Byte, 
	[Chuva09Status]			Byte, 
	[Chuva10Status]			Byte, 
	[Chuva11Status]			Byte, 
	[Chuva12Status]			Byte, 
	[Chuva13Status]			Byte, 
	[Chuva14Status]			Byte, 
	[Chuva15Status]			Byte, 
	[Chuva16Status]			Byte, 
	[Chuva17Status]			Byte, 
	[Chuva18Status]			Byte, 
	[Chuva19Status]			Byte, 
	[Chuva20Status]			Byte, 
	[Chuva21Status]			Byte, 
	[Chuva22Status]			Byte, 
	[Chuva23Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Clima]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[ParametroClima]			Byte, 
	[Maxima]			Single, 
	[Minima]			Single, 
	[Media]			Single, 
	[Total]			Single, 
	[DiaMaxima]			Byte, 
	[DiaMinima]			Byte, 
	[NumDiasDeChuva]			Byte, 
	[MaximaStatus]			Byte, 
	[MinimaStatus]			Byte, 
	[MediaStatus]			Byte, 
	[TotalStatus]			Byte, 
	[NumDiasDeChuvaStatus]			Byte, 
	[Clima01]			Single, 
	[Clima02]			Single, 
	[Clima03]			Single, 
	[Clima04]			Single, 
	[Clima05]			Single, 
	[Clima06]			Single, 
	[Clima07]			Single, 
	[Clima08]			Single, 
	[Clima09]			Single, 
	[Clima10]			Single, 
	[Clima11]			Single, 
	[Clima12]			Single, 
	[Clima13]			Single, 
	[Clima14]			Single, 
	[Clima15]			Single, 
	[Clima16]			Single, 
	[Clima17]			Single, 
	[Clima18]			Single, 
	[Clima19]			Single, 
	[Clima20]			Single, 
	[Clima21]			Single, 
	[Clima22]			Single, 
	[Clima23]			Single, 
	[Clima24]			Single, 
	[Clima25]			Single, 
	[Clima26]			Single, 
	[Clima27]			Single, 
	[Clima28]			Single, 
	[Clima29]			Single, 
	[Clima30]			Single, 
	[Clima31]			Single, 
	[Clima01Status]			Byte, 
	[Clima02Status]			Byte, 
	[Clima03Status]			Byte, 
	[Clima04Status]			Byte, 
	[Clima05Status]			Byte, 
	[Clima06Status]			Byte, 
	[Clima07Status]			Byte, 
	[Clima08Status]			Byte, 
	[Clima09Status]			Byte, 
	[Clima10Status]			Byte, 
	[Clima11Status]			Byte, 
	[Clima12Status]			Byte, 
	[Clima13Status]			Byte, 
	[Clima14Status]			Byte, 
	[Clima15Status]			Byte, 
	[Clima16Status]			Byte, 
	[Clima17Status]			Byte, 
	[Clima18Status]			Byte, 
	[Clima19Status]			Byte, 
	[Clima20Status]			Byte, 
	[Clima21Status]			Byte, 
	[Clima22Status]			Byte, 
	[Clima23Status]			Byte, 
	[Clima24Status]			Byte, 
	[Clima25Status]			Byte, 
	[Clima26Status]			Byte, 
	[Clima27Status]			Byte, 
	[Clima28Status]			Byte, 
	[Clima29Status]			Byte, 
	[Clima30Status]			Byte, 
	[Clima31Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Cotas24]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[TipoMedicaoCotas]			Byte, 
	[Maxima]			Single, 
	[Minima]			Single, 
	[Media]			Single, 
	[HoraMaxima]			Byte, 
	[HoraMinima]			Byte, 
	[MaximaStatus]			Byte, 
	[MinimaStatus]			Byte, 
	[MediaStatus]			Byte, 
	[Cota00]			Single, 
	[Cota01]			Single, 
	[Cota02]			Single, 
	[Cota03]			Single, 
	[Cota04]			Single, 
	[Cota05]			Single, 
	[Cota06]			Single, 
	[Cota07]			Single, 
	[Cota08]			Single, 
	[Cota09]			Single, 
	[Cota10]			Single, 
	[Cota11]			Single, 
	[Cota12]			Single, 
	[Cota13]			Single, 
	[Cota14]			Single, 
	[Cota15]			Single, 
	[Cota16]			Single, 
	[Cota17]			Single, 
	[Cota18]			Single, 
	[Cota19]			Single, 
	[Cota20]			Single, 
	[Cota21]			Single, 
	[Cota22]			Single, 
	[Cota23]			Single, 
	[Cota00Status]			Byte, 
	[Cota01Status]			Byte, 
	[Cota02Status]			Byte, 
	[Cota03Status]			Byte, 
	[Cota04Status]			Byte, 
	[Cota05Status]			Byte, 
	[Cota06Status]			Byte, 
	[Cota07Status]			Byte, 
	[Cota08Status]			Byte, 
	[Cota09Status]			Byte, 
	[Cota10Status]			Byte, 
	[Cota11Status]			Byte, 
	[Cota12Status]			Byte, 
	[Cota13Status]			Byte, 
	[Cota14Status]			Byte, 
	[Cota15Status]			Byte, 
	[Cota16Status]			Byte, 
	[Cota17Status]			Byte, 
	[Cota18Status]			Byte, 
	[Cota19Status]			Byte, 
	[Cota20Status]			Byte, 
	[Cota21Status]			Byte, 
	[Cota22Status]			Byte, 
	[Cota23Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [CurvaDescarga]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[PeriodoValidadeInicio]			DateTime, 
	[PeriodoValidadeFim]			DateTime, 
	[CotaMaxima]			Single, 
	[CotaMinima]			Single, 
	[TipoCurva]			Byte, 
	[NumeroCurva]			Text(5),
	[TipoEquacao]			Byte, 
	[CoefA]			Double, 
	[CoefH0]			Double, 
	[CoefN]			Double, 
	[CoefA0]			Double, 
	[CoefA1]			Double, 
	[CoefA2]			Double, 
	[CoefA3]			Double, 
	[TabelaPassoCota]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [CurvaDescargaTabelaVazao]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Vazao]			Single, 
	[Cota]			Double, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Entidade]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long,
	[Sigla]			Text(15),
	[Nome]			Text(100),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Estacao]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[BaciaCodigo]			Long,
	[SubBaciaCodigo]			Long,
	[RioCodigo]			Long,
	[EstadoCodigo]			Long,
	[MunicipioCodigo]			Long,
	[ResponsavelCodigo]			Long,
	[ResponsavelUnidade]			Integer, 
	[ResponsavelJurisdicao]			Integer, 
	[OperadoraCodigo]			Long,
	[OperadoraUnidade]			Integer, 
	[OperadoraSubUnidade]			Integer, 
	[TipoEstacao]			Byte, 
	[Codigo]			Long,
	[Nome]			Text(50),
	[CodigoAdicional]			Text(15),
	[Latitude]			Double, 
	[Longitude]			Double, 
	[Altitude]			Double, 
	[AreaDrenagem]			Double, 
	[TipoEstacaoEscala]			Byte, 
	[TipoEstacaoRegistradorNivel]			Byte, 
	[TipoEstacaoDescLiquida]			Byte, 
	[TipoEstacaoSedimentos]			Byte, 
	[TipoEstacaoQualAgua]			Byte, 
	[TipoEstacaoPluviometro]			Byte, 
	[TipoEstacaoRegistradorChuva]			Byte, 
	[TipoEstacaoTanqueEvapo]			Byte, 
	[TipoEstacaoClimatologica]			Byte, 
	[TipoEstacaoPiezometria]			Byte, 
	[TipoEstacaoTelemetrica]			Byte, 
	[PeriodoEscalaInicio]			DateTime, 
	[PeriodoEscalaFim]			DateTime, 
	[PeriodoRegistradorNivelInicio]			DateTime, 
	[PeriodoRegistradorNivelFim]			DateTime, 
	[PeriodoDescLiquidaInicio]			DateTime, 
	[PeriodoDescLiquidaFim]			DateTime, 
	[PeriodoSedimentosInicio]			DateTime, 
	[PeriodoSedimentosFim]			DateTime, 
	[PeriodoQualAguaInicio]			DateTime, 
	[PeriodoQualAguaFim]			DateTime, 
	[PeriodoPluviometroInicio]			DateTime, 
	[PeriodoPluviometroFim]			DateTime, 
	[PeriodoRegistradorChuvaInicio]			DateTime, 
	[PeriodoRegistradorChuvaFim]			DateTime, 
	[PeriodoTanqueEvapoInicio]			DateTime, 
	[PeriodoTanqueEvapoFim]			DateTime, 
	[PeriodoClimatologicaInicio]			DateTime, 
	[PeriodoClimatologicaFim]			DateTime, 
	[PeriodoPiezometriaInicio]			DateTime, 
	[PeriodoPiezometriaFim]			DateTime, 
	[PeriodoTelemetricaInicio]			DateTime, 
	[PeriodoTelemetricaFim]			DateTime, 
	[TipoRedeBasica]			Byte, 
	[TipoRedeEnergetica]			Byte, 
	[TipoRedeNavegacao]			Byte, 
	[TipoRedeCursoDagua]			Byte, 
	[TipoRedeEstrategica]			Byte, 
	[TipoRedeCaptacao]			Byte, 
	[TipoRedeSedimentos]			Byte, 
	[TipoRedeQualAgua]			Byte, 
	[TipoRedeClasseVazao]			Byte, 
	[UltimaAtualizacao]			DateTime, 
	[Operando]			Byte, 
	[Descricao]			HYPERLINK,
	[Historico]			HYPERLINK,
	[NumImagens]			Long,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Estado]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long,
	[CodigoIBGE]			Long,
	[Sigla]			Text(2),
	[Nome]			Text(50),
	[DataIns]			DateTime,
	[DataAlt]			DateTime,
	[RespAlt]			Integer
);

CREATE TABLE [fichadescritiva]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[dataficha]			DateTime, 
	[estacaocodigo]			Long NOT NULL,
	[novaestacao]			Text(1),
	[estacaonome]			Text(100),
	[roteiro]			Byte, 
	[tipoestacao]			Text(1),
	[codigoadicional]			Text(20),
	[cursodaguacodigo]			Long,
	[baciaCodigo]			Long NOT NULL,
	[subbaciaCodigo]			Long NOT NULL,
	[estadoCodigo]			Long NOT NULL,
	[municipioCodigo]			Long NOT NULL,
	[responsavelCodigo]			Long NOT NULL,
	[operadoraCodigo]			Long NOT NULL,
	[nomerio]			Text(150),
	[estacaoareadrenagem]			Long,
	[latitude]			Double, 
	[longitude]			Double, 
	[altitude]			Long,
	[MetodoPlanimetricoCodigo]			Byte, 
	[MetodoAltimetricoCodigo]			Byte, 
	[localizacao]			HYPERLINK,
	[acessabilidade]			HYPERLINK,
	[infraestrutura]			HYPERLINK,
	[potomografia]			HYPERLINK,
	[observadorCodigo]			Long NOT NULL,
	[secaoregua]			Text(1),
	[nlance]			Long,
	[lanceinstalado]			Text(100),
	[margem]			Text(1),
	[amplitute]			Long,
	[descricaolance]			HYPERLINK,
	[transbordamentomargemdireita]			Long,
	[transbordamentomargemesquerda]			Long,
	[referencianivel]			Text(1),
	[secaomedicaostatus]			Text(1),
	[secaocontrolestatus]			Text(1),
	[hidraulicoBControleCodigo]			Long,
	[hidraulicoBDistanciaRegua]			Long,
	[hidraulicoBLocalizacaoCodigo]			Long,
	[hidraulicoBDescricao]			HYPERLINK,
	[hidraulicoMControleCodigo]			Long,
	[hidraulicoMDistanciaRegua]			Long,
	[hidraulicoMLocalizacaoCodigo]			Long,
	[hidraulicoMDescricao]			HYPERLINK,
	[hidraulicoAControleCodigo]			Long,
	[hidraulicoADistanciaRegua]			Long,
	[hidraulicoALocalizacaoCodigo]			Long,
	[hidraulicoADescricao]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [fichaequipamento]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[fichadescritivacodigo]			Double NOT NULL, 
	[FichaMonitoramentoCodigo]			Double NOT NULL, 
	[tipoequipamentoCodigo]			Long NOT NULL,
	[TipoMarcaCodigo]			Long NOT NULL,
	[TipoModeloCodigo]			Long NOT NULL,
	[nserie]			Double, 
	[npatrimonio]			Double, 
	[dataativacao]			DateTime, 
	[datadesativacao]			DateTime, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [fichamonitoramento]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[fichadescritivacodigo]			Double, 
	[responsavelCodigo]			Long NOT NULL,
	[dataativacao]			DateTime, 
	[datadesativacao]			DateTime, 
	[tipomonitoramentoCodigo]			Long NOT NULL,
	[metodoobtencaoCodigo]			Long NOT NULL,
	[formatransmissaoCodigo]			Long NOT NULL,
	[latitude]			Double, 
	[longitude]			Double, 
	[altitude]			Long,
	[MetodoPlanimetricoCodigo]			Long,
	[MetodoAltimetricoCodigo]			Long,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [fichareferencianivel]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[fichadescritivacodigo]			Double, 
	[rn]			Long,
	[cota]			Long,
	[estabilidade]			Text(1),
	[altitude]			Long,
	[MetodoAltimetricoCodigo]			Long,
	[descricao]			Text(200),
	[observacao]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [fichasecaomedicao]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[fichadescritivacodigo]			Double, 
	[distanciasecaoregua]			Long,
	[localizacaoCodigo]			Long NOT NULL,
	[tipotravessiapredominanteCodigo]			Long NOT NULL,
	[distanciaPIPF]			Long,
	[naturezaleitoCodigo]			Long NOT NULL,
	[processomedicaoCodigo]			Long NOT NULL,
	[regimeCodigo]			Long NOT NULL,
	[ConformacaoCodigo]			Long NOT NULL,
	[Fundo]			Long,
	[MargemDNaturezaCodigo]			Long NOT NULL,
	[MargemDVegetacaoCodigo]			Long NOT NULL,
	[MargemDInclinacaoCodigo]			Long NOT NULL,
	[MargemENaturezaCodigo]			Long NOT NULL,
	[MargemEVegetacaoCodigo]			Long NOT NULL,
	[MargemEInclinacaoCodigo]			Long NOT NULL,
	[Observacao]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [Granulometria]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[HoraInicial]			DateTime, 
	[HoraFinal]			DateTime, 
	[Cota]			Single, 
	[Largura]			Single, 
	[TipoAmostra]			Byte, 
	[TipoColeta]			Text(50),
	[TipoEquip]			Text(50),
	[ProfTotal]			Single, 
	[OrdemColeta]			Long,
	[DistPTOInicial]			Single, 
	[ChuvaUlt48]			Byte, 
	[MatFundo15_9]			Single, 
	[MatFundo8_0]			Single, 
	[MatFundo4_0]			Single, 
	[MatFundo2_0]			Single, 
	[MatFundo1_0]			Single, 
	[MatFundo0_5]			Single, 
	[MatFundo0_25]			Single, 
	[MatFundo0_125]			Single, 
	[MatFundo0_0625]			Single, 
	[MatFundoArgila]			Single, 
	[MatFundoSilte]			Single, 
	[MatFundoAreia]			Single, 
	[MatFundoPedregulho]			Single, 
	[MatFundo0_0_a_0_0156]			Single, 
	[MatFundo0_0157_a_0_02]			Single, 
	[MatFundo0_0201_a_0_0625]			Single, 
	[MatFundo0_0626_a_0_1250]			Single, 
	[MatFundo0_1251_a_0_25]			Single, 
	[MatFundo0_2501_a_0_5]			Single, 
	[MatFundo0_501_a_1_0]			Single, 
	[MatFundo1_0001_a_2_0]			Single, 
	[MatFundo2_0001_a_4_0]			Single, 
	[MatFundo4_0001_a_8_0]			Single, 
	[MatFundo8_0001_a_16_000]			Single, 
	[MatFundoD10]			Single, 
	[MatFundoD16]			Single, 
	[MatFundoD35]			Single, 
	[MatFundoD50]			Single, 
	[MatFundoD65]			Single, 
	[MatFundoD84]			Single, 
	[MatFundoD90]			Single, 
	[MatArrasteVazao]			Single, 
	[MatArrasteLargRio]			Single, 
	[MatArrasteLargEquip]			Single, 
	[MatArrastePesoMat]			Single, 
	[MatArrasteVelMedia]			Single, 
	[MatArrasteTempAgua]			Single, 
	[MatArrasteTempAr]			Single, 
	[MatArrasteTempoColeta]			Single, 
	[MatArrasteArraste]			Single, 
	[MatArraste15_9]			Single, 
	[MatArraste8_0]			Single, 
	[MatArraste4_0]			Single, 
	[MatArraste2_0]			Single, 
	[MatArraste1_0]			Single, 
	[MatArraste0_5]			Single, 
	[MatArraste0_25]			Single, 
	[MatArraste0_125]			Single, 
	[MatArraste0_0625]			Single, 
	[MatArrasteArgila]			Single, 
	[MatArrasteSilte]			Single, 
	[MatArrasteAreia]			Single, 
	[MatArrastePedregulho]			Single, 
	[MatArraste0_0_a_0_0156]			Single, 
	[MatArraste0_0157_a_0_02]			Single, 
	[MatArraste0_0201_a_0_0625]			Single, 
	[MatArraste0_0626_a_0_1250]			Single, 
	[MatArraste0_1251_a_0_25]			Single, 
	[MatArraste0_2501_a_0_5]			Single, 
	[MatArraste0_501_a_1_0]			Single, 
	[MatArraste1_0001_a_2_0]			Single, 
	[MatArraste2_0001_a_4_0]			Single, 
	[MatArraste4_0001_a_8_0]			Single, 
	[MatArraste8_0001_a_16_000]			Single, 
	[MatArrasteD10]			Single, 
	[MatArrasteD16]			Single, 
	[MatArrasteD35]			Single, 
	[MatArrasteD50]			Single, 
	[MatArrasteD65]			Single, 
	[MatArrasteD84]			Single, 
	[MatArrasteD90]			Single, 
	[MatSusp15_9]			Single, 
	[MatSusp8_0]			Single, 
	[MatSusp4_0]			Single, 
	[MatSusp2_0]			Single, 
	[MatSusp1_0]			Single, 
	[MatSusp0_5]			Single, 
	[MatSusp0_25]			Single, 
	[MatSusp0_125]			Single, 
	[MatSusp0_0625]			Single, 
	[MatSuspArgila]			Single, 
	[MatSuspSilte]			Single, 
	[MatSuspAreia]			Single, 
	[MatSuspPedregulho]			Single, 
	[MatSusp0_0_a_0_0156]			Single, 
	[MatSusp0_0157_a_0_02]			Single, 
	[MatSusp0_0201_a_0_0625]			Single, 
	[MatSusp0_0626_a_0_1250]			Single, 
	[MatSusp0_1251_a_0_25]			Single, 
	[MatSusp0_2501_a_0_5]			Single, 
	[MatSusp0_501_a_1_0]			Single, 
	[MatSusp1_0001_a_2_0]			Single, 
	[MatSusp2_0001_a_4_0]			Single, 
	[MatSusp4_0001_a_8_0]			Single, 
	[MatSusp8_0001_a_16_000]			Single, 
	[MatSuspD10]			Single, 
	[MatSuspD16]			Single, 
	[MatSuspD35]			Single, 
	[MatSuspD50]			Single, 
	[MatSuspD65]			Single, 
	[MatSuspD84]			Single, 
	[MatSuspD90]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Identificadores]
 (
	[RegistroID]			Double NOT NULL, 
	[UsuarioID]			Double NOT NULL, 
	[ImagemID]			Double NOT NULL
);

CREATE TABLE [MedDescADCP]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[SecaoMedicao]			Long,
	[SecaoRegua]			Long,
	[NumMedicoes]			Long,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [MedDescADCPMedicao]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Num]			Long,
	[HoraInicio]			DateTime, 
	[HoraFim]			DateTime, 
	[ArqDados]			Text(255),
	[ArqConf]			Text(255),
	[EnsembleInicio]			Single, 
	[EnsembleFim]			Single, 
	[MargensInicio]			Single, 
	[MargensFim]			Single, 
	[Nivel1]			Single, 
	[Nivel2]			Single, 
	[QT]			Single, 
	[AQ]			Single, 
	[QM]			Single, 
	[Q]			Single, 
	[Qmedia]			Single, 
	[Area]			Single, 
	[Larg]			Single, 
	[Prof]			Single, 
	[VelMedia]			Single, 
	[M]			Single, 
	[DesvPad]			Single, 
	[CV]			Single, 
	[Obs]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [MedDescMolinete]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[HoraInicial]			DateTime, 
	[HoraFinal]			DateTime, 
	[SM]			Long,
	[CotaInicial]			Single, 
	[CotaFinal]			Single, 
	[Delta]			Single, 
	[Lastro]			Single, 
	[MargemInicial]			Byte, 
	[TipoMedicao]			Byte, 
	[Equipe]			Text(255),
	[NumVerticais]			Long,
	[PrimDist]			Single, 
	[Variacao]			Single, 
	[TempoConst]			Single, 
	[PINA]			Single, 
	[NAPF]			Single, 
	[MetodoCalc]			Byte, 
	[LimiteInf]			Single, 
	[LimiteSup]			Single, 
	[a1]			Single, 
	[b1]			Single, 
	[a2]			Single, 
	[b2]			Single, 
	[a3]			Single, 
	[b3]			Single, 
	[InfoMolinete]			Text(255),
	[RotToque]			Single, 
	[Aferido]			Text(255),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [MedDescMolineteVert]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Num]			Long,
	[DistAc]			Single, 
	[LeitHodFundo]			Single, 
	[Arrasto]			Single, 
	[ProfReal]			Single, 
	[NumPontos]			Long,
	[Toque1]			Single, 
	[Tempo1]			Single, 
	[Toque2]			Single, 
	[Tempo2]			Single, 
	[Toque3]			Single, 
	[Tempo3]			Single, 
	[Toque4]			Single, 
	[Tempo4]			Single, 
	[Toque5]			Single, 
	[Tempo5]			Single, 
	[Toque6]			Single, 
	[Tempo6]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [MedDescSol]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[HoraInicial]			DateTime, 
	[HoraFinal]			DateTime, 
	[SM]			Long,
	[Cota]			Single, 
	[ChuvaUlt48]			Byte, 
	[NatAmostra]			Byte, 
	[IdentificPTO]			Long,
	[InicioCol]			Byte, 
	[TipoAmostra]			Byte, 
	[DistBicoFundo]			Long,
	[TipoEquip]			Text(50),
	[DiamBocal]			Long,
	[MetodoCol]			Byte, 
	[AnaliseLab]			Byte, 
	[SolDissMedios]			Double, 
	[Lab]			Text(50),
	[TempAgua]			Single, 
	[TempAr]			Single, 
	[CondEletrica]			Double, 
	[ConcAmostraExtra]			Double, 
	[DataLiq]			DateTime, 
	[HoraLiq]			DateTime, 
	[NumAmostras]			Long,
	[ConcMedia]			Double, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [MetodoObtencao]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(50),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [modeloequipamento]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(100),
	[MarcaCodigo]			Long NOT NULL,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [Municipio]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstadoCodigo]			Long,
	[Codigo]			Long,
	[CodigoIBGE]			Long,
	[Nome]			Text(50),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [PerfilTransversal]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[NumLevantamento]			Long,
	[TipoSecao]			Byte, 
	[NumVerticais]			Long,
	[DistanciaPIPF]			Single, 
	[EixoXDistMaxima]			Single, 
	[EixoXDistMinima]			Single, 
	[EixoYCotaMaxima]			Single, 
	[EixoYCotaMinima]			Single, 
	[ElmGeomPassoCota]			Single, 
	[Observacoes]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [PerfilTransversalVert]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Distancia]			Single, 
	[Cota]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [PlanTrab]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Ano]			Long,
	[ResponsavelCodigo]			Long,
	[ResponsavelSigla]			Text(15),
	[ResponsavelUnidade]			Integer, 
	[ResponsavelUnidadeSigla]			Text(50),
	[OperadoraCodigo]			Long,
	[OperadoraSigla]			Text(15),
	[OperadoraUnidade]			Integer, 
	[OperadoraUnidadeSigla]			Text(50),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [PlanTrabPonto]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Roteiro]			Integer, 
	[CodigoFLU]			Long,
	[CodigoPLU]			Long,
	[ColetaFLU]			Text(12),
	[ColetaPLU]			Text(12),
	[NumVisitas]			Integer, 
	[NumNivelamentos]			Integer, 
	[NumMedLiquidas]			Integer, 
	[NumMedSolidas]			Integer, 
	[NumMedQualAgua]			Integer, 
	[NumLevantSecaoMedicao]			Integer, 
	[NumLevantSecaoEscala]			Integer, 
	[MedExtrasMenorQue]			Single, 
	[MedExtrasMaiorQue]			Single, 
	[MesVisita01]			Byte, 
	[MesVisita02]			Byte, 
	[MesVisita03]			Byte, 
	[MesVisita04]			Byte, 
	[MesVisita05]			Byte, 
	[MesVisita06]			Byte, 
	[MesVisita07]			Byte, 
	[MesVisita08]			Byte, 
	[MesVisita09]			Byte, 
	[MesVisita10]			Byte, 
	[MesVisita11]			Byte, 
	[MesVisita12]			Byte, 
	[Observacoes]			Text(255),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [QualAgua]
 (
	[RegistroID]			Double, 
	[Importado]			Byte, 
	[Temporario]			Byte, 
	[Removido]			Byte, 
	[ImportadoRepetido]			Byte, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[NumMedicao]			Long,
	[PosHorizColeta]			Byte, 
	[PosVertColeta]			Byte, 
	[Choveu]			Byte, 
	[Profundidade]			Single, 
	[TempAr]			Single, 
	[TempAmostra]			Single, 
	[pH]			Single, 
	[Cor]			Single, 
	[Turbidez]			Single, 
	[CondutividadeEletrica]			Single, 
	[DurezaTotal]			Single, 
	[Dureza]			Single, 
	[DQO]			Single, 
	[DBO]			Single, 
	[OD]			Single, 
	[SolTotais]			Single, 
	[SolFixos]			Single, 
	[SolVolateis]			Single, 
	[SolSuspensaoTotais]			Single, 
	[SolSuspensaoFixos]			Single, 
	[SolSuspensaoVolateis]			Single, 
	[SolDissolvidosTotais]			Single, 
	[SolDissolvidosFixos]			Single, 
	[SolDissolvidosVolateis]			Single, 
	[SolSedimentaveis]			Single, 
	[Detergentes]			Single, 
	[AlcalinidadeCO3]			Single, 
	[AlcalinidadeHCO3]			Single, 
	[AlcalinidadeOH]			Single, 
	[Cloretos]			Single, 
	[Sulfatos]			Single, 
	[Sulfetos]			Single, 
	[Fluoretos]			Single, 
	[FosfatoTotal]			Single, 
	[Cianetos]			Single, 
	[NitrogenioTotal]			Single, 
	[AmoniaNaoIonizavel]			Single, 
	[NitrogenioAmoniacal]			Single, 
	[Nitratos]			Single, 
	[Nitritos]			Single, 
	[CompostosOrganoclorados]			Single, 
	[CompostosOrganofosforados]			Single, 
	[Aluminio]			Single, 
	[Arsenio]			Single, 
	[Cadmio]			Single, 
	[Chumbo]			Single, 
	[Cobre]			Single, 
	[CromoTrivalente]			Single, 
	[CromoHexavalente]			Single, 
	[Manganes]			Single, 
	[Mercurio]			Single, 
	[Niquel]			Single, 
	[Zinco]			Single, 
	[IndiceFenois]			Single, 
	[ColiformesTotais]			Single, 
	[ColiformesFecais]			Single, 
	[CloroResidual]			Single, 
	[Bario]			Single, 
	[Berilio]			Single, 
	[Boro]			Single, 
	[Cobalto]			Single, 
	[Estanho]			Single, 
	[Litio]			Single, 
	[Prata]			Single, 
	[Selenio]			Single, 
	[UranioTotal]			Single, 
	[Vanadio]			Single, 
	[Benzeno]			Single, 
	[BenzoAPireno]			Single, 
	[n11Dicloroeteno]			Single, 
	[n12Dicloroetano]			Single, 
	[Pentaclorofenol]			Single, 
	[Tetracloroeteno]			Single, 
	[Tricloroeteno]			Single, 
	[TetracloretoCarbono]			Single, 
	[n246Triclorofenol]			Single, 
	[Aldrin]			Single, 
	[Clordano]			Single, 
	[DDT]			Single, 
	[Dieldrin]			Single, 
	[Endrin]			Single, 
	[Endossulfan]			Single, 
	[EpoxidoHeptacloro]			Single, 
	[Heptacloro]			Single, 
	[Lindano]			Single, 
	[Metoxicloro]			Single, 
	[DodecacloroNonacloro]			Single, 
	[BifenilasPolicloradas]			Single, 
	[Toxafeno]			Single, 
	[Demeton]			Single, 
	[Gution]			Single, 
	[Malation]			Single, 
	[Paration]			Single, 
	[Carbaril]			Single, 
	[Acido24Diclorofenoxiacetico]			Single, 
	[n245TP]			Single, 
	[n245T]			Single, 
	[BHC]			Single, 
	[Ethion]			Single, 
	[DySystonDisulfton]			Single, 
	[Phosdrin]			Single, 
	[DDEPP]			Single, 
	[AzinfosEtil]			Single, 
	[Diazinon]			Single, 
	[EstreptococosFecais]			Single, 
	[Salmonelas]			Single, 
	[Colifagos]			Single, 
	[BacteriasHeterotroficas]			Single, 
	[Protozoarios]			Single, 
	[Fungos]			Single, 
	[Algas]			Single, 
	[ContagemBacteriasPlaca]			Single, 
	[Clorofila]			Single, 
	[OleosGraxas]			Single, 
	[AlcalinidadeTotal]			Single, 
	[CarbonoOrganicoTotal]			Single, 
	[Hidrocarbonetos]			Single, 
	[OrtofosfatoTotal]			Single, 
	[CromoTotal]			Single, 
	[MetilParation]			Single, 
	[NitrogenioOrganico]			Single, 
	[SodioTotal]			Single, 
	[MagnesioTotal]			Single, 
	[SilicaDissolvida]			Single, 
	[PotassioTotal]			Single, 
	[CalcioTotal]			Single, 
	[FerroTotal]			Single, 
	[DescargaLiquida]			Single, 
	[FosforoTotal]			Single, 
	[BismutoTotal]			Single, 
	[Acidez]			Single, 
	[NitrogenioTotalKJELDAHL]			Single, 
	[NitrogenioAlbuminoide]			Single, 
	[Transparencia]			Single, 
	[EnteroBacteriasPatogenicas]			Single, 
	[ZooplanctonTotal]			Single, 
	[Amoniaco]			Single, 
	[IQA]			Single, 
	[DataAlt]			DateTime, 
	[DataIns]			DateTime, 
	[RespAlt]			Integer, 
	[ColiformesTermotolerantes]			Single, 
	[Escherichia]			Single, 
	[Aluminiodissolvido]			Single, 
	[Borodissolvido]			Single, 
	[Cianetolivre]			Single, 
	[Cobredissolvido]			Single, 
	[CondutividadeEspecifica]			Single, 
	[Densidadecianobacterias]			Single, 
	[Durezamagnesio]			Single, 
	[FerroDissolvido]			Single, 
	[FitoplanctonQuantitativo]			Single, 
	[ODsaturacao]			Single, 
	[ParametroProfundidade]			Single
);

CREATE TABLE [QualAguaStatus]
 (
	[RegistroID]			Double, 
	[Removido]			Byte, 
	[QualAgua001Status]			Byte, 
	[QualAgua002Status]			Byte, 
	[QualAgua003Status]			Byte, 
	[QualAgua004Status]			Byte, 
	[QualAgua005Status]			Byte, 
	[QualAgua006Status]			Byte, 
	[QualAgua007Status]			Byte, 
	[QualAgua008Status]			Byte, 
	[QualAgua009Status]			Byte, 
	[QualAgua010Status]			Byte, 
	[QualAgua011Status]			Byte, 
	[QualAgua012Status]			Byte, 
	[QualAgua013Status]			Byte, 
	[QualAgua014Status]			Byte, 
	[QualAgua015Status]			Byte, 
	[QualAgua016Status]			Byte, 
	[QualAgua017Status]			Byte, 
	[QualAgua018Status]			Byte, 
	[QualAgua019Status]			Byte, 
	[QualAgua020Status]			Byte, 
	[QualAgua021Status]			Byte, 
	[QualAgua022Status]			Byte, 
	[QualAgua023Status]			Byte, 
	[QualAgua024Status]			Byte, 
	[QualAgua025Status]			Byte, 
	[QualAgua026Status]			Byte, 
	[QualAgua027Status]			Byte, 
	[QualAgua028Status]			Byte, 
	[QualAgua029Status]			Byte, 
	[QualAgua030Status]			Byte, 
	[QualAgua031Status]			Byte, 
	[QualAgua032Status]			Byte, 
	[QualAgua033Status]			Byte, 
	[QualAgua034Status]			Byte, 
	[QualAgua035Status]			Byte, 
	[QualAgua036Status]			Byte, 
	[QualAgua037Status]			Byte, 
	[QualAgua038Status]			Byte, 
	[QualAgua039Status]			Byte, 
	[QualAgua040Status]			Byte, 
	[QualAgua041Status]			Byte, 
	[QualAgua042Status]			Byte, 
	[QualAgua043Status]			Byte, 
	[QualAgua044Status]			Byte, 
	[QualAgua045Status]			Byte, 
	[QualAgua046Status]			Byte, 
	[QualAgua047Status]			Byte, 
	[QualAgua048Status]			Byte, 
	[QualAgua049Status]			Byte, 
	[QualAgua050Status]			Byte, 
	[QualAgua051Status]			Byte, 
	[QualAgua052Status]			Byte, 
	[QualAgua053Status]			Byte, 
	[QualAgua054Status]			Byte, 
	[QualAgua055Status]			Byte, 
	[QualAgua056Status]			Byte, 
	[QualAgua057Status]			Byte, 
	[QualAgua058Status]			Byte, 
	[QualAgua059Status]			Byte, 
	[QualAgua060Status]			Byte, 
	[QualAgua061Status]			Byte, 
	[QualAgua062Status]			Byte, 
	[QualAgua063Status]			Byte, 
	[QualAgua064Status]			Byte, 
	[QualAgua065Status]			Byte, 
	[QualAgua066Status]			Byte, 
	[QualAgua067Status]			Byte, 
	[QualAgua068Status]			Byte, 
	[QualAgua069Status]			Byte, 
	[QualAgua070Status]			Byte, 
	[QualAgua071Status]			Byte, 
	[QualAgua072Status]			Byte, 
	[QualAgua073Status]			Byte, 
	[QualAgua074Status]			Byte, 
	[QualAgua075Status]			Byte, 
	[QualAgua076Status]			Byte, 
	[QualAgua077Status]			Byte, 
	[QualAgua078Status]			Byte, 
	[QualAgua079Status]			Byte, 
	[QualAgua080Status]			Byte, 
	[QualAgua081Status]			Byte, 
	[QualAgua082Status]			Byte, 
	[QualAgua083Status]			Byte, 
	[QualAgua084Status]			Byte, 
	[QualAgua085Status]			Byte, 
	[QualAgua086Status]			Byte, 
	[QualAgua087Status]			Byte, 
	[QualAgua088Status]			Byte, 
	[QualAgua089Status]			Byte, 
	[QualAgua090Status]			Byte, 
	[QualAgua091Status]			Byte, 
	[QualAgua092Status]			Byte, 
	[QualAgua093Status]			Byte, 
	[QualAgua094Status]			Byte, 
	[QualAgua095Status]			Byte, 
	[QualAgua096Status]			Byte, 
	[QualAgua097Status]			Byte, 
	[QualAgua098Status]			Byte, 
	[QualAgua099Status]			Byte, 
	[QualAgua100Status]			Byte, 
	[QualAgua101Status]			Byte, 
	[QualAgua102Status]			Byte, 
	[QualAgua103Status]			Byte, 
	[QualAgua104Status]			Byte, 
	[QualAgua105Status]			Byte, 
	[QualAgua106Status]			Byte, 
	[QualAgua107Status]			Byte, 
	[QualAgua108Status]			Byte, 
	[QualAgua109Status]			Byte, 
	[QualAgua110Status]			Byte, 
	[QualAgua111Status]			Byte, 
	[QualAgua112Status]			Byte, 
	[QualAgua113Status]			Byte, 
	[QualAgua114Status]			Byte, 
	[QualAgua115Status]			Byte, 
	[QualAgua116Status]			Byte, 
	[QualAgua117Status]			Byte, 
	[QualAgua118Status]			Byte, 
	[QualAgua119Status]			Byte, 
	[QualAgua120Status]			Byte, 
	[QualAgua121Status]			Byte, 
	[QualAgua122Status]			Byte, 
	[QualAgua123Status]			Byte, 
	[QualAgua124Status]			Byte, 
	[QualAgua125Status]			Byte, 
	[QualAgua126Status]			Byte, 
	[QualAgua127Status]			Byte, 
	[QualAgua128Status]			Byte, 
	[QualAgua129Status]			Byte, 
	[QualAgua130Status]			Byte, 
	[QualAgua131Status]			Byte, 
	[QualAgua132Status]			Byte, 
	[QualAgua133Status]			Byte, 
	[QualAgua134Status]			Byte, 
	[QualAgua135Status]			Byte, 
	[QualAgua136Status]			Byte, 
	[QualAgua137Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer, 
	[QualAgua138Status]			Byte, 
	[QualAgua139Status]			Byte, 
	[QualAgua140Status]			Byte, 
	[QualAgua141Status]			Byte, 
	[QualAgua142Status]			Byte, 
	[QualAgua143Status]			Byte, 
	[QualAgua144Status]			Byte, 
	[QualAgua145Status]			Byte, 
	[QualAgua146Status]			Byte, 
	[QualAgua147Status]			Byte
);

CREATE TABLE [Rio]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[BaciaCodigo]			Long,
	[SubBaciaCodigo]			Long,
	[Codigo]			Long,
	[Nome]			Text(50),
	[Jurisdicao]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [RioEstado0101]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[EstadoCodigo]			Long NOT NULL
);

CREATE TABLE [Sedimentos]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[NumMedicao]			Long,
	[DataLiq]			DateTime, 
	[HoraLiq]			DateTime, 
	[NumMedicaoLiq]			Long,
	[Cota]			Single, 
	[Vazao]			Single, 
	[AreaMolhada]			Single, 
	[Largura]			Single, 
	[VelMedia]			Single, 
	[ConcentracaoMatSuspensao]			Double, 
	[CotaDeMedicao]			Single, 
	[TemperaturaDaAgua]			Single, 
	[ConcentracaoDaAmostraExtra]			Double, 
	[CondutividadeEletrica]			Double, 
	[Observacoes]			HYPERLINK,
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Temp]
 (
	[idTemp]			Long,
	[idEstacao]			Long,
	[data]			Text(255),
	[cota]			Double
);

CREATE TABLE [TEMP2]
 (
	[EstacaoCodigo]			Long,
	[mes]			Long,
	[ano]			Long,
	[Media]			Double
);

CREATE TABLE [TEMP3]
 (
	[EstacaoCodigo]			Long,
	[mes]			Long,
	[ano]			Long,
	[Media]			Double
);

CREATE TABLE [TipoEquipamento]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(100),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [TipoFormaTransmissao]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(100),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [tipomonitoramento]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(100),
	[Sigla]			Text(20),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [Usuario]
 (
	[UsuarioID]			Double NOT NULL, 
	[TipoUsuario]			Byte NOT NULL, 
	[Nome]			Text(100),
	[Empresa]			Text(100),
	[Departamento]			Text(100),
	[Telefone]			Text(100),
	[Email]			Text(100),
	[Conta]			Text(64) NOT NULL,
	[Senha]			Text(64) NOT NULL
);

CREATE TABLE [Vazoes]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[MediaDiaria]			Byte, 
	[MetodoObtencaoVazoes]			Byte, 
	[Maxima]			Single, 
	[Minima]			Single, 
	[Media]			Single, 
	[DiaMaxima]			Byte, 
	[DiaMinima]			Byte, 
	[MaximaStatus]			Byte, 
	[MinimaStatus]			Byte, 
	[MediaStatus]			Byte, 
	[MediaAnual]			Single, 
	[MediaAnualStatus]			Byte, 
	[Vazao01]			Single, 
	[Vazao02]			Single, 
	[Vazao03]			Single, 
	[Vazao04]			Single, 
	[Vazao05]			Single, 
	[Vazao06]			Single, 
	[Vazao07]			Single, 
	[Vazao08]			Single, 
	[Vazao09]			Single, 
	[Vazao10]			Single, 
	[Vazao11]			Single, 
	[Vazao12]			Single, 
	[Vazao13]			Single, 
	[Vazao14]			Single, 
	[Vazao15]			Single, 
	[Vazao16]			Single, 
	[Vazao17]			Single, 
	[Vazao18]			Single, 
	[Vazao19]			Single, 
	[Vazao20]			Single, 
	[Vazao21]			Single, 
	[Vazao22]			Single, 
	[Vazao23]			Single, 
	[Vazao24]			Single, 
	[Vazao25]			Single, 
	[Vazao26]			Single, 
	[Vazao27]			Single, 
	[Vazao28]			Single, 
	[Vazao29]			Single, 
	[Vazao30]			Single, 
	[Vazao31]			Single, 
	[Vazao01Status]			Byte, 
	[Vazao02Status]			Byte, 
	[Vazao03Status]			Byte, 
	[Vazao04Status]			Byte, 
	[Vazao05Status]			Byte, 
	[Vazao06Status]			Byte, 
	[Vazao07Status]			Byte, 
	[Vazao08Status]			Byte, 
	[Vazao09Status]			Byte, 
	[Vazao10Status]			Byte, 
	[Vazao11Status]			Byte, 
	[Vazao12Status]			Byte, 
	[Vazao13Status]			Byte, 
	[Vazao14Status]			Byte, 
	[Vazao15Status]			Byte, 
	[Vazao16Status]			Byte, 
	[Vazao17Status]			Byte, 
	[Vazao18Status]			Byte, 
	[Vazao19Status]			Byte, 
	[Vazao20Status]			Byte, 
	[Vazao21Status]			Byte, 
	[Vazao22Status]			Byte, 
	[Vazao23Status]			Byte, 
	[Vazao24Status]			Byte, 
	[Vazao25Status]			Byte, 
	[Vazao26Status]			Byte, 
	[Vazao27Status]			Byte, 
	[Vazao28Status]			Byte, 
	[Vazao29Status]			Byte, 
	[Vazao30Status]			Byte, 
	[Vazao31Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Vazoes24]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[MediaDiaria]			Byte, 
	[MetodoObtencaoVazoes]			Byte, 
	[Maxima]			Single, 
	[Minima]			Single, 
	[Media]			Single, 
	[HoraMaxima]			Byte, 
	[HoraMinima]			Long,
	[DiaMinima]			Byte, 
	[MaximaStatus]			Byte, 
	[MinimaStatus]			Byte, 
	[MediaStatus]			Byte, 
	[MediaAnual]			Single, 
	[MediaAnualStatus]			Byte, 
	[Vazao01]			Single, 
	[Vazao02]			Single, 
	[Vazao03]			Single, 
	[Vazao04]			Single, 
	[Vazao05]			Single, 
	[Vazao06]			Single, 
	[Vazao07]			Single, 
	[Vazao08]			Single, 
	[Vazao09]			Single, 
	[Vazao10]			Single, 
	[Vazao11]			Single, 
	[Vazao12]			Single, 
	[Vazao13]			Single, 
	[Vazao14]			Single, 
	[Vazao15]			Single, 
	[Vazao16]			Single, 
	[Vazao17]			Single, 
	[Vazao18]			Single, 
	[Vazao19]			Single, 
	[Vazao20]			Single, 
	[Vazao21]			Single, 
	[Vazao22]			Single, 
	[Vazao23]			Single, 
	[Vazao24]			Single, 
	[Vazao01Status]			Byte, 
	[Vazao02Status]			Byte, 
	[Vazao03Status]			Byte, 
	[Vazao04Status]			Byte, 
	[Vazao05Status]			Byte, 
	[Vazao06Status]			Byte, 
	[Vazao07Status]			Byte, 
	[Vazao08Status]			Byte, 
	[Vazao09Status]			Byte, 
	[Vazao10Status]			Byte, 
	[Vazao11Status]			Byte, 
	[Vazao12Status]			Byte, 
	[Vazao13Status]			Byte, 
	[Vazao14Status]			Byte, 
	[Vazao15Status]			Byte, 
	[Vazao16Status]			Byte, 
	[Vazao17Status]			Byte, 
	[Vazao18Status]			Byte, 
	[Vazao19Status]			Byte, 
	[Vazao20Status]			Byte, 
	[Vazao21Status]			Byte, 
	[Vazao22Status]			Byte, 
	[Vazao23Status]			Byte, 
	[Vazao24Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Versao]
 (
	[Versao]			Text(50) NOT NULL,
	[Modificacoes]			HYPERLINK
);

CREATE TABLE [Cotas]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[MediaDiaria]			Byte, 
	[TipoMedicaoCotas]			Byte, 
	[Maxima]			Single, 
	[Minima]			Single, 
	[Media]			Single, 
	[DiaMaxima]			Byte, 
	[DiaMinima]			Byte, 
	[MaximaStatus]			Byte, 
	[MinimaStatus]			Byte, 
	[MediaStatus]			Byte, 
	[MediaAnual]			Single, 
	[MediaAnualStatus]			Byte, 
	[Cota01]			Single, 
	[Cota02]			Single, 
	[Cota03]			Single, 
	[Cota04]			Single, 
	[Cota05]			Single, 
	[Cota06]			Single, 
	[Cota07]			Single, 
	[Cota08]			Single, 
	[Cota09]			Single, 
	[Cota10]			Single, 
	[Cota11]			Single, 
	[Cota12]			Single, 
	[Cota13]			Single, 
	[Cota14]			Single, 
	[Cota15]			Single, 
	[Cota16]			Single, 
	[Cota17]			Single, 
	[Cota18]			Single, 
	[Cota19]			Single, 
	[Cota20]			Single, 
	[Cota21]			Single, 
	[Cota22]			Single, 
	[Cota23]			Single, 
	[Cota24]			Single, 
	[Cota25]			Single, 
	[Cota26]			Single, 
	[Cota27]			Single, 
	[Cota28]			Single, 
	[Cota29]			Single, 
	[Cota30]			Single, 
	[Cota31]			Single, 
	[Cota01Status]			Byte, 
	[Cota02Status]			Byte, 
	[Cota03Status]			Byte, 
	[Cota04Status]			Byte, 
	[Cota05Status]			Byte, 
	[Cota06Status]			Byte, 
	[Cota07Status]			Byte, 
	[Cota08Status]			Byte, 
	[Cota09Status]			Byte, 
	[Cota10Status]			Byte, 
	[Cota11Status]			Byte, 
	[Cota12Status]			Byte, 
	[Cota13Status]			Byte, 
	[Cota14Status]			Byte, 
	[Cota15Status]			Byte, 
	[Cota16Status]			Byte, 
	[Cota17Status]			Byte, 
	[Cota18Status]			Byte, 
	[Cota19Status]			Byte, 
	[Cota20Status]			Byte, 
	[Cota21Status]			Byte, 
	[Cota22Status]			Byte, 
	[Cota23Status]			Byte, 
	[Cota24Status]			Byte, 
	[Cota25Status]			Byte, 
	[Cota26Status]			Byte, 
	[Cota27Status]			Byte, 
	[Cota28Status]			Byte, 
	[Cota29Status]			Byte, 
	[Cota30Status]			Byte, 
	[Cota31Status]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [fichaimagem]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[fichadescritivacodigo]			Double, 
	[tipoimagemcodigo]			Text(1),
	[nomeresponsavel]			Text(100),
	[data]			DateTime, 
	[imagem]			OLE (255), 
	[descricao]			Text(200),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [Imagem]
 (
	[ImagemID]			Double NOT NULL, 
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[TipoRegistro]			Byte NOT NULL, 
	[Nome]			Text(100),
	[TipoImagem]			Byte NOT NULL, 
	[Bits]			OLE (255)
);

CREATE TABLE [MedDescSolAmostra]
 (
	[RegistroID]			Double NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[Num]			Long,
	[Duracao]			Single, 
	[DistPI]			Single, 
	[ProfCol]			Single, 
	[ConcSolSusp]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [Observador]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[CodigoCPF]			Double NOT NULL, 
	[Nome]			Text(100),
	[dtnascimento]			DateTime, 
	[apelido]			Text(100),
	[leiturista]			Text(100),
	[leituristaObservador]			Text(1),
	[InicioLeitura]			DateTime, 
	[FimLeitura]			DateTime, 
	[cep]			Text(8),
	[endereco]			Text(200),
	[bairro]			Text(100),
	[estadocodigo]			Long,
	[municipiocodigo]			Long,
	[distanciaestacao]			Double, 
	[telcelular]			Text(11),
	[telresidencial]			Text(11),
	[telcomercial]			Text(11),
	[Latitude]			Double, 
	[Longitude]			Double, 
	[Altitude]			Double, 
	[instrucaoCodigo]			Byte, 
	[MetodoPlanimetricoCodigo]			Byte, 
	[MetodoAltimetricoCodigo]			Byte, 
	[Observacao]			Text(100),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);

CREATE TABLE [ResumoDescarga]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[EstacaoCodigo]			Long,
	[NivelConsistencia]			Byte, 
	[Data]			DateTime, 
	[Hora]			DateTime, 
	[NumMedicao]			Long,
	[Cota]			Single, 
	[Vazao]			Single, 
	[AreaMolhada]			Single, 
	[Largura]			Single, 
	[VelMedia]			Single, 
	[Profundidade]			Single, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer, 
	[Tecnico]			Text(255),
	[MedidorVazao]			Long
);

CREATE TABLE [SubBacia]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[BaciaCodigo]			Long,
	[Codigo]			Long,
	[Nome]			Text(50),
	[Jurisdicao]			Byte, 
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Integer
);

CREATE TABLE [TipoMarca]
 (
	[RegistroID]			Double NOT NULL, 
	[Importado]			Byte NOT NULL, 
	[Temporario]			Byte NOT NULL, 
	[Removido]			Byte NOT NULL, 
	[ImportadoRepetido]			Byte NOT NULL, 
	[Codigo]			Long NOT NULL,
	[Nome]			Text(100),
	[DataIns]			DateTime, 
	[DataAlt]			DateTime, 
	[RespAlt]			Byte
);
