[project]
name = "HidroDB"
version = "0.0.0"
dependencies = ["requests", "sqlalchemy"]

[project.optional-dependencies]
dev     = ["pydoc-markdown", "pytest", "pytest-cov"]
release = ["python-semantic-release"]

[tool.setuptools.packages.find]
include = ["hidrodb"]

[tool.semantic_release]
version_toml = ["pyproject.toml:project.version"]
branch = "main"
commit_parser = "conventional"
allow_zero_version = true

[tool.semantic_release.commit_parser_options]
minor_tags = ["feat"]
patch_tags = ["fix"]
parse_squash_commits = true
ignore_merge_commits = true

[tool.pytest.ini_options]
testpaths        = ["tests"]
python_files     = ["test_*.py"]
python_functions = ["test_*"]

[tool.coverage.run]
source = ["hidrodb"]

[[tool.pydoc-markdown.loaders]]
type = "python"
search_path = [ "./hidrodb" ]

[tool.pydoc-markdown.renderer]
type = "mkdocs"
output_directory = "wiki"
content_directory_name = "./"
mkdocs_config = {site_name = "HidroDB", repo_url  = "https://github.com/ctxmc/hidrodb"}

[[tool.pydoc-markdown.renderer.pages]]
title  = "Home"
name   = "Home"
source = "README.md"

[[tool.pydoc-markdown.renderer.pages]]
title    = "Jobs"
name     = "jobs"
contents = ['jobs.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "Client Database"
name     = "client database"
contents = ['database.client.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "Hidro Database"
name     = "hidro database"
contents = ['database.hidro.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "WebServices"
name     = "webservices"
contents = ['webservices.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "Config"
name     = "config"
contents = ['config.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "Client Models"
name     = "client models"
contents = ['models.client.*']

[[tool.pydoc-markdown.renderer.pages]]
title    = "Hidro Models"
name     = "hidro models"
contents = ['models.hidro.*']